name: libyang2
on: push
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@feature/61-re-use-repository-and-ref-parameter
    with:
      ref: feature/61-re-use-repository-and-ref-parameter
      source: git+https://github.com/CESNET/libyang/
      debian_source: native
      git_filter: v[0-9\.]*$
      git_tag_match: v([0-9\-]*)
